"""Add ai_summary_count to User model

Revision ID: 0c875b71e2d9
Revises: d05fa1122697
Create Date: 2025-03-23 21:32:23.468214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c875b71e2d9'
down_revision = 'd05fa1122697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_summary_count')

    # ### end Alembic commands ###
