"""Initial migration

Revision ID: 7d5a508aa5c2
Revises: 
Create Date: 2025-03-12 23:08:45.034217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5a508aa5c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.drop_column('twitter_post_id')
        batch_op.drop_column('twitter_credentials')
        batch_op.drop_column('media_paths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_paths', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('twitter_credentials', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('twitter_post_id', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
