"""Add sent_at column to saved_summary table

Revision ID: 880beff74388
Revises: 7d5a508aa5c2
Create Date: 2025-03-13 00:51:09.327340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880beff74388'
down_revision = '7d5a508aa5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_summary', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
